const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('state:get'),
  pickSounds: () => ipcRenderer.invoke('sounds:pick'),
  checkFiles: (files) =>
    ipcRenderer.invoke('sounds:check', Array.from(files).map((f) => webUtils.getPathForFile(f))),
  readAudio: (src) => ipcRenderer.invoke('sounds:read', src),
  addSound: (draft) => ipcRenderer.invoke('sounds:add', draft),
  updateSound: (id, patch) => ipcRenderer.invoke('sounds:update', id, patch),
  removeSound: (id) => ipcRenderer.invoke('sounds:remove', id),
  removeSounds: (ids) => ipcRenderer.invoke('sounds:removeMany', ids),
  setVolumes: (ids, volume) => ipcRenderer.invoke('sounds:volumeMany', ids, volume),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  createProfile: (name) => ipcRenderer.invoke('profiles:create', name),
  updateProfile: (id, patch) => ipcRenderer.invoke('profiles:update', id, patch),
  removeProfile: (id) => ipcRenderer.invoke('profiles:remove', id),
  switchProfile: (id) => ipcRenderer.invoke('profiles:switch', id),
  exportProfile: (id) => ipcRenderer.invoke('profiles:export', id),
  importProfile: () => ipcRenderer.invoke('profiles:import', null),
  importProfileFile: (file) => ipcRenderer.invoke('profiles:import', webUtils.getPathForFile(file)),
  exportBackup: () => ipcRenderer.invoke('backup:export'),
  restoreBackup: () => ipcRenderer.invoke('backup:restore'),
  setCapturing: (on) => ipcRenderer.invoke('capture:set', on),
  identifyKeyboard: () => ipcRenderer.invoke('keyboard:identify'),
  cancelIdentify: () => ipcRenderer.invoke('keyboard:cancel'),
  onPlay: (cb) => ipcRenderer.on('play', (_e, id) => cb(id)),
  onStopAll: (cb) => ipcRenderer.on('stop-all', () => cb()),
  onDeviceKey: (cb) => ipcRenderer.on('device-key', (_e, key) => cb(key)),
  onState: (cb) => ipcRenderer.on('state', (_e, state) => cb(state)),
  platform: process.platform,
  initialTheme: process.argv.find((a) => a.startsWith('--sb-theme='))?.split('=')[1] || 'system',
});
